name: YaguBogu Android CI

on:
  push:
    branches: [ "dev-an" ]
  pull_request:
    branches: [ "dev-an" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew build

    - name: Run ktlint check
      run: ./gradlew ktlintCheck
