name: Backend CI

on:
  workflow_call:
    secrets:
      APPLICATION_YML:
        required: true
      TEST_APPLICATION_YML:
        required: true
      SERVER_IP:
        required: false
      SSH_USER:
        required: false
      SSH_PRIVATE_KEY:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Set application.yml
        run: |
          mkdir -p src/main/resources
          mkdir -p src/test/resources
          echo "${{ secrets.APPLICATION_YML }}" > ./src/main/resources/application.yml
          echo "${{ secrets.TEST_APPLICATION_YML }}" > ./src/test/resources/application.yml

      - name: Gradle Caching
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew clean build

      - name: Rename jar
        run: mv ./build/libs/*SNAPSHOT.jar ./backend-build.jar
