name: YaguBogu Backend dev-be

# 0. workflow 실행 트리거
on:
  push:
    branches: [ "dev-be" ]
    path:
      - 'backend/**'
  pull_request:
    branches: [ "dev-be" ]
    path:
      - 'backend/**'
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/backend-ci.yml
    secrets: inherit
