name: YaguBogu Backend dev

# 0. workflow 실행 트리거
on:
  push:
    branches: [ "dev" ]
    path:
      - 'backend/**'
  workflow_dispatch:

# 1. 배포
jobs:
  build:
    uses: ./.github/workflows/backend-ci.yml
    secrets: inherit

  deploy:
    runs-on: self-hosted
    needs: build
    defaults:
      run:
        working-directory: backend

    steps:
      - name: 80포트 프로세스 종료
        run: |
          sudo fuser -k -n tcp 80 || true

      - name: 서버 실행
        run: |
          sudo nohup java -jar /home/ubuntu/backend-build.jar > /home/ubuntu/output.log 2>&1 &
