name: YaguBogu Backend Dev

on:
  push:
    branches: [ "docker-test" ]
    paths:
      - "backend/**"
  workflow_dispatch:

env:
  IMAGE: yagubogu/yagubogu-backend

jobs:
  ci:
    runs-on: ubuntu-22.04-arm
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'corretto'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_DEPLOY_USERNAME }}
          password: ${{ secrets.DOCKERHUB_DEPLOY_TOKEN }}

      - name: Docker Image Build & Push (arm64-arch)
        run: |
          TAG_LATEST="dev-latest"
          # Dockerfile 경로: backend/Dockerfile
          docker buildx build \
          --progress=plain \
          --cache-from=type=gha --cache-to=type=gha,mode=max \
          -f Dockerfile \
          --platform linux/arm64 \
          -t $IMAGE:$TAG_LATEST \
          --push \
          .
